# Generated by Django 3.0.4 on 2020-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='templat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=40)),
                ('tempcontent', models.CharField(max_length=10000)),
                ('priority', models.IntegerField()),
                ('multiplepasses', models.BooleanField()),
                ('starttime', models.IntegerField()),
            ],
        ),
    ]
